### ISSUE TITLE
I can't open the dds files.

### ISSUE THREAD

**Issue by YoshiCrystal** [aboood40091/BFLIM-Extractor#3]
I can't open the output dds files, I open them on paint.net and I have this error: File is not a supported DDS format

Any ideas to solve this? BFLIM that I was using: https://mega.nz/#!7cYjSbIZ!GFx-8IsGPyCmVWUJDefl5lIYQIRBfOBWPt1aUevOVMc

Also I have the same problem with the BNTX Extractor... Thanks in advance.

**Comment by aboood40091** [comment]
Don't use Paint.NET. If you want to use it badly, I recommend using GIMP, Compressonator, or Noesis to convert the DDS to PNG, and then open the PNG in Paint.NET.
